Qe 14 socket
ascepanovic/qmonorepo pull request #17
Opened 2023-06-15 14:55 UTC by popovic65

2023-06-15 15:29 UTC, ascepanovic requested changes

2023-06-15 15:29 UTC, ascepanovic commented on backend/src/controllers/auth.controller.ts
> +          expires: new Date(Date.now() + 24 * 60 * 60 * 1000),
must be configurable as env variable -> amount of hours or minutes

2023-06-15 15:29 UTC, ascepanovic commented on backend/src/controllers/game.controller.ts
> +    const games = await findAll();
all ? not smart

2023-06-15 15:29 UTC, ascepanovic commented on backend/src/routes/category.route.ts
> + * /api/category/{id}:
LIKE it, good!

2023-06-15 15:29 UTC, ascepanovic commented on backend/src/services/user.service.ts
> +          game_status: "WAITING",
do not use strings hardcoded here, call it somehow

2023-06-15 19:36 UTC, ascepanovic commented on backend/src/controllers/auth.controller.ts
> +          expires: new Date(Date.now() + 24 * 60 * 60 * 1000),
or even as db variable within table app_configuration

2023-06-15 19:37 UTC, ascepanovic commented on backend/src/services/user.service.ts
> +          game_status: "WAITING",
somehow as constant from somewhere -> pseudo: **GameStatus.WAITING**

2023-06-16 07:33 UTC, popovic65 commented on backend/src/controllers/game.controller.ts
> +    const games = await findAll();
Kako treba da bude? Ovu rutu bi admin koristio

2023-06-16 07:38 UTC, ascepanovic commented on backend/src/controllers/game.controller.ts
> +    const games = await findAll();
@popovic65 moraces da imas neki limit ili paging, all ce vratiti sve rezultate od jednom, bez obzira sto je admin, i sto sada imamo jednu igru, takva prakasa u BE-u nije dobra, da vratis sve, gotovo nikad osim ako znas da se novi inserti ne desavaju a cak i tada stavljas limit.

2023-06-16 08:46 UTC, ascepanovic approved these changes

2023-06-16 08:47 UTC, merged